// <auto-generated />
using Chronica.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chronica.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20250610023827_AddTipo")]
    partial class AddTipo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Chronica.Models.Classe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImagemURL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Chronica.Models.Habilidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Habilidade");
                });

            modelBuilder.Entity("Chronica.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImagemURL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("Chronica.Models.Origem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImagemURL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Origem");
                });

            modelBuilder.Entity("Chronica.Models.Pericia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Pericia");
                });

            modelBuilder.Entity("Chronica.Models.Personagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Agilidade")
                        .HasColumnType("int");

                    b.Property<string>("Aparencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Carisma")
                        .HasColumnType("int");

                    b.Property<int?>("ClasseId")
                        .HasColumnType("int");

                    b.Property<int>("Constituicao")
                        .HasColumnType("int");

                    b.Property<int>("Espirito")
                        .HasColumnType("int");

                    b.Property<int>("Forca")
                        .HasColumnType("int");

                    b.Property<string>("Historia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("ImagemURL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Intelecto")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Objetivos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrigemId")
                        .HasColumnType("int");

                    b.Property<string>("Personalidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PontosAtributo")
                        .HasColumnType("int");

                    b.Property<string>("TipoPersonagem")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<int?>("VarianteRacialId")
                        .HasColumnType("int");

                    b.Property<int>("Vida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId");

                    b.HasIndex("OrigemId");

                    b.HasIndex("VarianteRacialId");

                    b.ToTable("Personagens");

                    b.HasDiscriminator<string>("TipoPersonagem").HasValue("Personagem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Chronica.Models.PersonagemHabilidade", b =>
                {
                    b.Property<int>("PersonagemId")
                        .HasColumnType("int");

                    b.Property<int>("HabilidadeTipoId")
                        .HasColumnType("int");

                    b.HasKey("PersonagemId", "HabilidadeTipoId");

                    b.HasIndex("HabilidadeTipoId");

                    b.ToTable("PersonagemHabilidade");
                });

            modelBuilder.Entity("Chronica.Models.PersonagemItem", b =>
                {
                    b.Property<int>("PersonagemId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("PersonagemId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("PersonagemItem");
                });

            modelBuilder.Entity("Chronica.Models.PersonagemPericia", b =>
                {
                    b.Property<int>("PersonagemId")
                        .HasColumnType("int");

                    b.Property<int>("PericiaId")
                        .HasColumnType("int");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PersonagemId", "PericiaId");

                    b.HasIndex("PericiaId");

                    b.ToTable("PersonagemPericia");
                });

            modelBuilder.Entity("Chronica.Models.PersonagemSubHabilidade", b =>
                {
                    b.Property<int>("PersonagemId")
                        .HasColumnType("int");

                    b.Property<int>("SubHabilidadeId")
                        .HasColumnType("int");

                    b.HasKey("PersonagemId", "SubHabilidadeId");

                    b.HasIndex("SubHabilidadeId");

                    b.ToTable("PersonagemSubHabilidade");
                });

            modelBuilder.Entity("Chronica.Models.SubHabilidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("HabilidadeId")
                        .HasColumnType("int");

                    b.Property<string>("ImagemURL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HabilidadeId");

                    b.ToTable("SubHabilidades");
                });

            modelBuilder.Entity("Chronica.Models.VarianteRacial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImagemURL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("VariantesRaciais");
                });

            modelBuilder.Entity("Chronica.Models.AgentesModel", b =>
                {
                    b.HasBaseType("Chronica.Models.Personagem");

                    b.Property<string>("Jogador")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Agente");
                });

            modelBuilder.Entity("Chronica.Models.AmeacasModel", b =>
                {
                    b.HasBaseType("Chronica.Models.Personagem");

                    b.Property<string>("NivelDificuldade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoAmeaca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Ameaca");
                });

            modelBuilder.Entity("Chronica.Models.Personagem", b =>
                {
                    b.HasOne("Chronica.Models.Classe", "Classe")
                        .WithMany("Personagens")
                        .HasForeignKey("ClasseId");

                    b.HasOne("Chronica.Models.Origem", "Origem")
                        .WithMany("Personagens")
                        .HasForeignKey("OrigemId");

                    b.HasOne("Chronica.Models.VarianteRacial", "VarianteRacial")
                        .WithMany("Personagens")
                        .HasForeignKey("VarianteRacialId");

                    b.Navigation("Classe");

                    b.Navigation("Origem");

                    b.Navigation("VarianteRacial");
                });

            modelBuilder.Entity("Chronica.Models.PersonagemHabilidade", b =>
                {
                    b.HasOne("Chronica.Models.Habilidade", "Habilidade")
                        .WithMany("PersonagemHabilidades")
                        .HasForeignKey("HabilidadeTipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronica.Models.Personagem", "Personagem")
                        .WithMany("PersonagemHabilidades")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidade");

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Chronica.Models.PersonagemItem", b =>
                {
                    b.HasOne("Chronica.Models.Item", "Item")
                        .WithMany("PersonagemItens")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronica.Models.Personagem", "Personagem")
                        .WithMany("PersonagemItens")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Chronica.Models.PersonagemPericia", b =>
                {
                    b.HasOne("Chronica.Models.Pericia", "Pericia")
                        .WithMany("PersonagemPericias")
                        .HasForeignKey("PericiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronica.Models.Personagem", "Personagem")
                        .WithMany("PersonagemPericias")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pericia");

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Chronica.Models.PersonagemSubHabilidade", b =>
                {
                    b.HasOne("Chronica.Models.Personagem", "Personagem")
                        .WithMany("PersonagemSubHabilidades")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronica.Models.SubHabilidade", "SubHabilidade")
                        .WithMany("PersonagemSubHabilidades")
                        .HasForeignKey("SubHabilidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");

                    b.Navigation("SubHabilidade");
                });

            modelBuilder.Entity("Chronica.Models.SubHabilidade", b =>
                {
                    b.HasOne("Chronica.Models.Habilidade", "Habilidade")
                        .WithMany("SubHabilidades")
                        .HasForeignKey("HabilidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidade");
                });

            modelBuilder.Entity("Chronica.Models.Classe", b =>
                {
                    b.Navigation("Personagens");
                });

            modelBuilder.Entity("Chronica.Models.Habilidade", b =>
                {
                    b.Navigation("PersonagemHabilidades");

                    b.Navigation("SubHabilidades");
                });

            modelBuilder.Entity("Chronica.Models.Item", b =>
                {
                    b.Navigation("PersonagemItens");
                });

            modelBuilder.Entity("Chronica.Models.Origem", b =>
                {
                    b.Navigation("Personagens");
                });

            modelBuilder.Entity("Chronica.Models.Pericia", b =>
                {
                    b.Navigation("PersonagemPericias");
                });

            modelBuilder.Entity("Chronica.Models.Personagem", b =>
                {
                    b.Navigation("PersonagemHabilidades");

                    b.Navigation("PersonagemItens");

                    b.Navigation("PersonagemPericias");

                    b.Navigation("PersonagemSubHabilidades");
                });

            modelBuilder.Entity("Chronica.Models.SubHabilidade", b =>
                {
                    b.Navigation("PersonagemSubHabilidades");
                });

            modelBuilder.Entity("Chronica.Models.VarianteRacial", b =>
                {
                    b.Navigation("Personagens");
                });
#pragma warning restore 612, 618
        }
    }
}
